---
deployment:
  tasks:
    - export APP=/home/gsmtron1/public_html/jour/application/
    - /bin/cp -R application/controllers $APP
    - /bin/cp -R application/helpers $APP
    - /bin/cp -R application/models $APP
    - /bin/cp -R application/views $APP
    - export ASSETS=/home/gsmtron1/public_html/jour/
    - /bin/cp -R assets $ASSETS
    - export APPKTR=/home/gsmtron1/public_html/jour_ktr/application/
    - /bin/cp -R application/controllers $APPKTR
    - /bin/cp -R application/helpers $APPKTR
    - /bin/cp -R application/models $APPKTR
    - /bin/cp -R application/views $APPKTR
    - export ASSETSKTR=/home/gsmtron1/public_html/jour_ktr/
    - /bin/cp -R assets $ASSETSKTR
