---
deployment:
  tasks:
    - export APP=/home/gsmtron1/public_html/jour/application/
    - /bin/cp -R application/controllers $APP
    - /bin/cp -R application/helpers $APP
    - /bin/cp -R application/models $APP
    - /bin/cp -R application/views $APP
    - /bin/cp -R application/third_party $APP
    - /bin/cp -R application/libraries $APP
    - export ASSETS=/home/gsmtron1/public_html/jour/
    - /bin/cp -R assets $ASSETS
    - /bin/cp -R system $ASSETS
    - export APPKTR=/home/gsmtron1/public_html/jour_ktr/application/
    - /bin/cp -R application/controllers $APPKTR
    - /bin/cp -R application/helpers $APPKTR
    - /bin/cp -R application/models $APPKTR
    - /bin/cp -R application/views $APPKTR
    - /bin/cp -R application/third_party $APPKTR
    - /bin/cp -R application/libraries $APPKTR
    - export ASSETSKTR=/home/gsmtron1/public_html/jour_ktr/
    - /bin/cp -R assets $ASSETSKTR
    - /bin/cp -R system $ASSETSKTR
    - export APPSSC=/home/gsmtron1/public_html/jour_ssc/application/
    - /bin/cp -R application/controllers $APPSSC
    - /bin/cp -R application/helpers $APPSSC
    - /bin/cp -R application/models $APPSSC
    - /bin/cp -R application/views $APPSSC
    - /bin/cp -R application/third_party $APPSSC
    - /bin/cp -R application/libraries $APPSSC
    - export ASSETSSSC=/home/gsmtron1/public_html/jour_ssc/
    - /bin/cp -R assets $ASSETSSSC
    - /bin/cp -R system $ASSETSSSC
